# Generated by Django 5.1.4 on 2025-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desCat', models.CharField(max_length=30)),
                ('imageCat', models.CharField(max_length=250)),
            ],
        ),
    ]
