# Generated by Django 5.1.4 on 2025-03-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=17)),
                ('image', models.CharField(max_length=102)),
                ('previewDescription', models.CharField(max_length=112)),
                ('detailDescription', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('qtestock', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
    ]
